### ISSUE TITLE
Implementation of flatMap breaks the compilation

### ISSUE THREAD

**Issue by EdouardDubois** [poillic/live13_3wa#1]
Hello,

First of all thank you I've been using this project for a bit and it never failed me, it does exactly what it says in the documentation but recently I've been running into an issue.

After downloading the project I've try to run it on my local machine but the terminal does not seem to recognize it and crashed silently which is a pain to try and debug.

I was thinking it might be linked to the update of some of your dependencies.

Thank you,

**Comment by EdouardDubois** [comment]
@poillic did you happen check this error ?

**Comment by poillic** [comment]
Which cmd did yo uuse to start the project ?

**Comment by EdouardDubois** [comment]
I tried the command specified in the init file : npm lift tamer
